### ISSUE TITLE
Help: Infinite loop

### ISSUE THREAD

**Issue by hugo-leij** [albaintor/homeassistant_electrolux_status#20] opened 2024-02-07 08:40 UTC
Hi,

Just installed the plugin in but its in a infinite loop
<img width="355" alt="image" src="https://github.com/albaintor/homeassistant_electrolux_status/assets/10241984/bbd0999a-066a-438d-b952-e7f7103f211c">

How can is stop this

**Comment by albaintor** [comment] 2024-02-07 08:50
Hi,
which version did you install ? this problem has already been reported but I was unable to reproduce it. If you can send me the logs
Otherwise to fix it follow this procedure : https://github.com/albaintor/homeassistant_electrolux_status/discussions/6#discussioncomment-8373131

**Comment by joosthoi1** [comment] 2024-02-07 12:38
> Hi, which version did you install ? this problem has already been reported but I was unable to reproduce it. If you can send me the logs

Steps to reproduce:
1. Add integration
2. Enter wrong password
3. Infinite login loop

I tried deleting and disabling the login from the UI while the entries were still below 1000, but that didn't work, it didn't remove them.

**Comment by hugo-leij** [comment] 2024-02-07 13:26
Hi,

So i delete more than 100,000 lines in core.config_entries :-D Thnx for the solution @albaintor.

My steps

1. Edit a file in python file with text 
2. Restart HA 
3. Delete config/component/electrolux_status directory
4. Delete all the lines with vim (press V and scoll down).
5. install de addon again with the right username en password. 

While deleting, I saw my password was wrong :-O, so you are correct @joosthoi1 about the steps to reproduce.

**Comment by slingshot74** [comment] 2024-02-07 14:14
> 2\. homeassistant/.storage/core.config_entries

Can someone share a screenshot please? I can't find the .storage folder :)
Thanks!

**Comment by albaintor** [comment] 2024-02-07 14:20
It is hidden by default : from addon file editor, go to configuration options and remove the ".storage" entry from filter and restart the addon :
<img width="936" alt="image" src="https://github.com/albaintor/homeassistant_electrolux_status/assets/118518828/eb401a4a-fa01-4a4b-8021-90347283ae19">

**Comment by slingshot74** [comment] 2024-02-07 14:21
Ah !! Thanks!

**Comment by albaintor** [comment] 2024-02-07 14:37
Beware of not messing up with this file : don't forget to remove the trailing commas for instance.
Sorry for this mess, I can reproduce the problem now. I am on it

**Comment by albaintor** [comment] 2024-02-07 14:57
I fixed this in https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0.6

**Comment by slingshot74** [comment] 2024-02-07 17:12
I did the update and after that everything was unavailable.
I deleted the integration and add it again and everything is there again.

Do we need to delete the integration after each update?
For me no problem but then I know I should do this.

**Comment by albaintor** [comment] 2024-02-07 17:15
I have the same problem and this is new. I guess there is some instability on the websocket but maybe this is something else. I need to investigate

**Comment by albaintor** [comment] 2024-02-10 09:42
I close this issue as considered as fixed. I have not seen the "unavailable entities" behaviour again since and I have no info to investigate it with.

**Closed by albaintor** 2024-02-10 09:42 UTC
